default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['CZIG_DB_DEV'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: <%= ENV['CZIG_DB_TST'] %>

production:
  <<: *default
  host: localhost
  database: <%= ENV['CZIG_DB_PRD'] %>
